# https://docs.docker.com/compose/compose-file/
version: "3.8"

# network
# ja:コンテンツ内ネットワーク名称
# zh:这个是容器内局域网网络名
networks:
  dockertest-network:
    driver: bridge

services:
  ### frontend #################
  # ja:フロントエンド，ここの名称はコンテンツ内ネットワークでportとして使う
  # zh:前端文件，注意这里可以当作变量在局域网内使用
  frontend:
    container_name: depoly-frontend
    build:
      context: ./frontend
    ports:
      - 127.0.0.1:7021:7021
    restart: always
    depends_on:
      - backend
    networks:
      - dockertest-network

  ### backend #################
  # ja:バックエンド，ここの名称はコンテンツ内ネットワークでportとして使う
  # zh:后端文件，注意这里可以当作变量在局域网内使用
  backend:
    container_name: depoly-backend
    build:
      context: ./backend
    ports:
      - 127.0.0.1:7022:7022
    restart: always
    depends_on:
      - database
    networks:
      - dockertest-network

  ### database #################
  # ja:データベース，ここの名称はコンテンツ内ネットワークでportとして使う
  # zh:数据库，注意这里可以当作变量在局域网内使用
  database:
    container_name: depoly-database
    build:
      context: ./database
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
    networks:
      - dockertest-network
